services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    logging:
      driver: loki
      options:
        loki-url: "http://10.10.2.90:3100/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - /volume1/downloads:/downloads
      - /volume1/music:/music
      - /volume1/video:/video
    devices:
      - /dev/dri:/dev/dri  # GPU passthrough
    restart: unless-stopped