services:
  influxdb:
    container_name: influxdb
    restart: unless-stopped
    image: influxdb
    logging: 
      driver: loki
      options:
        loki-url: "http://10.10.2.90:3100/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    ports:
      - 8086:8086
    volumes:
      -  /home/jthairu/docker/influxdb/data:/var/lib/influxdb2
      - /home/jthairu/docker/influxdb/config:/etc/influxdb2
    networks:
      - monitor_network


  grafana:
    image: grafana/grafana:latest
    logging: 
      driver: loki
      options:
        loki-url: "http://10.10.2.90:3100/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /home/jthairu/docker/grafana:/var/lib/grafana
    user: "1000:1000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Mucii1311254*#
    networks:
      - monitor_network

  loki:
    image: grafana/loki
    container_name: loki
    hostname: loki
    restart: unless-stopped
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - "3100:3100"
    volumes:
      - /home/jthairu/docker/loki/config/config.yaml:/etc/loki/config.yaml:ro
      - /home/jthairu/docker/loki/data:/loki:rw
    networks:
      - monitor_network

  
  alloy:
    image: grafana/alloy:v1.10.2
    container_name: alloy
    hostname: alloy
    restart: unless-stopped
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    volumes:
      - /home/jthairu/docker/alloy/config:/etc/alloy/config
      - /home/jthairu/docker/alloy/data:/var/lib/alloy/data
      - /:/rootfs:ro
      - /run:/run:ro
      - /var/log:/var/log:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker/:ro
      - /run/udev/data:/run/udev/data:ro
    networks:
      - monitor_network

networks:
  monitor_network:
    driver: bridge
