networks:
  traefik_proxy:
    external: true

services:
  traefik:
    image: traefik:v3.5.2
    logging: 
      driver: loki
      options:
        loki-url: "http://10.10.2.90:3100/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    container_name: traefik
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    env_file:
      - /opt/traefik/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /opt/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /opt/traefik/acme.json:/etc/traefik/acme.json
      - /opt/traefik/log/:/var/log/traefik/
    environment:
      - AWS_ACCESS_KEY_ID=#
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION=#
    networks:
      - traefik_proxy
