networks:
  traefik_proxy:
    external: true

services:
  traefik:
    image: traefik:v3.5.2
    # logging section is commented out to allow traefik.yml to handle it
    container_name: traefik
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/jthairu/docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /home/jthairu/docker/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /home/jthairu/docker/traefik/acme.json:/etc/traefik/acme.json:rw
    environment:
      - AWS_ACCESS_KEY_ID=??
      - AWS_SECRET_ACCESS_KEY=??
      - AWS_REGION=??
    networks:
      - traefik_proxy
